spring:
  application:
    name: dating
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_system
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  exposed:
    show-sql: true
logging:
  level:
    root: info

