spring:
  application:
    name:
      spring_boot_ssm

  # Virtual threads are not working in netty
  threads:
    virtual:
      enabled: true


  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/ssm
    username: root
    password: root
  sql:
    init:
      mode: never

logging:
  level:
    root: info
    web: info
    org.jetbrains.exposed: trace

  pattern:
    console: "%yellow([%date{yyyy-MM-dd HH:mm:ss.SSS}]) %boldMagenta(${PID:- }) %esb(){APPLICATION_NAME}%esb{APPLICATION_GROUP} %boldBlue([%thread]) %green(%file:%line) %highlight(%-5level){FATAL=red, ERROR=bright-red, WARN=yellow, INFO=green, DEBUG=cyan, TRACE=blue} %cyan(%logger{36}) : %magenta(%msg%n)"
