package edu.tyut.dao;

import edu.tyut.bean.NewDept;
import edu.tyut.bean.NewDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    long countByExample(NewDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int deleteByExample(NewDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int insert(NewDept row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int insertSelective(NewDept row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    List<NewDept> selectByExample(NewDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    NewDept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int updateByExampleSelective(@Param("row") NewDept row, @Param("example") NewDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int updateByExample(@Param("row") NewDept row, @Param("example") NewDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int updateByPrimaryKeySelective(NewDept row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int updateByPrimaryKey(NewDept row);
}