package edu.tyut.dao;

import edu.tyut.bean.NewEmp;
import edu.tyut.bean.NewEmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    long countByExample(NewEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int deleteByExample(NewEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int insert(NewEmp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int insertSelective(NewEmp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    List<NewEmp> selectByExample(NewEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    NewEmp selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int updateByExampleSelective(@Param("row") NewEmp row, @Param("example") NewEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int updateByExample(@Param("row") NewEmp row, @Param("example") NewEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int updateByPrimaryKeySelective(NewEmp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Wed Dec 04 22:48:01 CST 2024
     */
    int updateByPrimaryKey(NewEmp row);
}