spring:
  application:
    name: springboot3-webflux-function
  threads:
    virtual:
      enabled: true
logging:
  level:
    root: info
  pattern:
    console: "%yellow([%date{yyyy-MM-dd HH:mm:ss}]) %blue([%thread]) %green(%file:%line) %highlight(%-5level){FATAL=red, ERROR=bright-red, WARN=yellow, INFO=green, DEBUG=cyan, TRACE=blue} %cyan(%logger{36}) : %magenta(%msg%n)"
